web:
  build: .
  command: 'bash -c ''java -Dserver.port=$PORT -jar  target/springAngular-1.0.0.jar'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
